## Project Config
---
# Databases Config
db:
    default:
        driver: pdo_mysql
        user: username
        password: password
        dbname: localhost
# Site config
site:
    # remove the "/" at the end
    url: "http://site.com"