## Routing Config
---
# Events Pages
onError:
    class: { Main:error }
# Pages
index_page:
    path: /
    class: { Main:main }
text_page:
    path: /
    class: { Main:text }
hello_page:
    pattern: "@/hello/(\w+)/@"
    class: { Main:hello }