language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_install:
  - composer self-update
  - composer --version
  - composer validate
  - composer install
before_script:
    # Go to settings
    - cd ./app/config/
    # Create configuration file
    - cp configuration.sample.yml configuration.yml
    # Change the debug mode
    - sed 's/false/true/g' configuration.yml
    # Now the test
    - cd ../../framework/test/
script:
  - phpunit --colors  --bootstrap "../../vendor/autoload.php" ./