language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
before_install:
    # Update Composer
    - composer self-update
    - composer --version
    # Update PHPUnit
    - wget https://phar.phpunit.de/phpunit.phar
    - php phpunit.phar --version
    # Validate file composer.json
    - composer validate
    # Install dependencies
    - composer install
    # Create test database
    - mysql -e 'create database test;'
    - mysql -u travis -p test < test.sql
before_script:
    # Go to settings
    - cd ./app/config/
    # Create configuration file
    - cp configuration.sample.yml configuration.yml
    # Change the debug mode
    - sed 's/false/true/g' configuration.yml
    # Root directory
    - cd ../../
script:
    # Running Tests
    - php phpunit.phar --coverage-clover=coverage.clover --colors  --bootstrap "./vendor/autoload.php" ./framework/test/
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover