language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_install:
  - composer self-update
  - composer --version
  - composer validate
  - composer install
before_script:
    - cd ./framework/test/
script:
  - phpunit --colors  --bootstrap "../../vendor/autoload.php" ./