language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_install:
    # Update Composer
  - composer self-update
  - composer --version
  # Update PHPUnit
  - phpunit --self-update
  - phpunit --version
  # Validate file composer.json
  - composer validate
  # Install dependencies
  - composer install
before_script:
    # Go to settings
    - cd ./app/config/
    # Create configuration file
    - cp configuration.sample.yml configuration.yml
    # Change the debug mode
    - sed 's/false/true/g' configuration.yml
    # Now the test
    - cd ../../framework/test/
script:
  - phpunit --coverage-clover=coverage.clover --colors  --bootstrap "../../vendor/autoload.php" ./
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover