## Project Config
---
# Environment type
environment:
    debug: true
# Databases Config
db:
    default:
        driver: pdo_mysql
        user: username
        password: password
        dbname: localhost
# Site config
site:
    # remove the "/" at the end
    url: "http://localhost:8080/iWorkPHPGit/iWorkPHP/www"
## Advanced
twig:
    ext:
        - Sample