## Project Config
---
# Environment type
environment:
    debug: true
# Databases Config
db:
    driver: pdo_mysql
    user: username
    password: password
    dbname: localhost
# Site config
site:
    # remove the "/" at the end
    url: "http://site.com"
## Advanced
twig:
    ext:
        - Sample